/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package enmyj.aoc;

public class App {
    public static String getGreeting(String greeting) {
        return greeting;
    }

    public static void main(String[] args) {

    }
}
