/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package enmyj.aoc;

import net.jqwik.api.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Property
    void appHasAGreeting(@ForAll String greeting) {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(greeting), greeting);
    }
}
